
## FINANCIAL DATA
MODULE 1 | LESSON 4


---

# **FROM A FINANCIAL ENGINEERING VIEW TO A MACHINE LEARNING VIEW**

|  |  |
|:---|:---|
|**Reading Time** |  30 minutes |
|**Prior Knowledge** | Structured Data, Unstructured Data  |
|**Keywords** | Flash Crash, Data Volume, Data Variety, Data Velocity, Data Veracity, Data Value |


---

*When you are in a shopping mall or airport terminal, you walk up to the information kiosk to find a map that says "You are here."  If we were to do so in the world of data, what would the map look like?  As financial engineers, where are we in the vast world of data? There is time series data, survey data, economic data, alternative data, big data. This lesson will attempt to answer that by examining data from the financial engineering perspective to the machine learning perspective. We'll begin by looking at desirable features of data.*<span style='color: transparent; font-size:1%'>All rights reserved WQU WorldQuant University QQQQ</span>

## **1. Data Quality**

As financial engineers, we think of data as information provided by markets. Those markets could be securities exchanges, over-the-counter markets, credit agencies, central banks, economic institutions, etc. The data can be provided by the exchanges themselves, broker-dealers with whom we trade, the agencies who make and sell the credit models, central banks, and economic institutions through their API portals. There are also third-party companies that use data to build factor models, or other value-added models that score or rank stocks, securities, factors, and sectors to assist in financial decision-making.
Regardless of the source, there are four features of data equality we always seek:

a.	Accuracy <br>
b.	Completeness <br>
c.	Consistency <br>
d.	Timeliness <br>

Suppose we were making a lending decision to a consumer.  How would we know the credit risks to determine a suitable credit limit, interest rate, and repayment terms? All four of the principles would apply. Here's how the four features would apply.

### **1.1 Accuracy**
First, we'd like to ensure that the data we have is about the person to whom we intend to loan funds. We'd want to make sure we have the correct individual and would rely on reference data pointing to the person (a national ID number).  Just as securities have their primary keys like CUSIPs or SEDOLs, people should have unique identification. We would want to make sure we don't mix up people with the same name or even family members with the same name who live at the same address.    

### **1.2 Completeness**
Second, we would want a complete history. Imagine if we only pulled credit reports say within the last 10 years for homes and other collateralized loans, but not for ordinary credit cards. We would have only a partial picture.  Completeness means that the lender has to perform due diligence to discover all information. Of course, regulation may prohibit a lender from getting information that is not allowed. For example, some credit prohibits a person's age or gender as a criterion for getting a loan.  These protected classes ensure fairness in lending.  Completeness must abide within the confines of what information is allowed, and find full histories.

### **1.3 Consistency**
Third, we would like the data that is provided from different sources to agree. As there are multiple companies that collect and provide credit ratings, we may want to pull from two or agencies to see if the data is consistent. Indeed, using multiple credit agencies we can correct for any discrepancies.

### **1.4 Timeliness**
Fourth, we would like the data to be timely. Suppose a customer applied for six different credit cards all within one morning. We would need to make sure our credit checks reflect real-time lending. Even data that is one day old would not show the extra credit or outstanding balance an individual may have. Such a system could be gamed, and ill-intentioned borrowers can get an inordinate amount of loans all within a short window of time, achieving a balance far beyond what would be accepted if they applied for these loans over a longer period of time. Indeed, the burden on many analytics providers now is that data analytics are performed in real-time. This requires not only the ability to handle real-time requests, but also the ability to run analyses that take a short time so that decisions can be made quickly. For example, many credit cards offer an opportunity for a credit increase and are able to provide an answer in under a minute.   

The computational and modeling burdens these demands place on the analysis require a thorough understanding of the data. In the next section, we'll start by reviewing structured data.

## **2. Structured Data**

In the last section, we discussed four principles of quality data. Let's apply these to structured data, the topic of our previous lesson.  

### **2.1 Accuracy**
We've been taught "garbage in, garbage out" as a reminder to incorporate accuracy. Clearly, if we have data that is well structured, but highly inaccurate, we have garbage coming out. Note that this is not merely useless. It is dangerous! Models that produce outputs that "seem" correct may be used for pricing and hedging and cause untold amounts of financial damage. Recall the operating hazard of mismatching price and quantity, resulting in a \$225 million dollar trading error. Had the model simply produced no output or warning messages, no trade would be executed and no money would be lost. Useless means a model has no use. Dangerous means a model can lose big time.  

### **2.2 Completeness**
What about completeness? Suppose we were measuring volatility. Imagine we included the week of the flash crash, but only looked at a frequency that misses the event, say weekly data. Would our data be complete? If we had decisions in place, such as stop-losses, then those could trigger when using live market prices, which we would not know with a volatility measure based on weekly returns. As you progress in your coursework through econometrics, stochastic modeling, and machine learning, you will be exposed to different frequencies of data. Volatility will look different at different time scales. Having a complete set of data will depend on your application.  


### **2.3 Consistency**
Likewise, consistency is key. Is data that comes from different sources the same? For example, suppose you had been closely monitoring the equity market in the U.S. On April 23, 2018, the news agency Associated Press had their Twitter account hacked.  The tweet read "Breaking: Two Explosions in the White House and Barack Obama is injured." The Dow Jones Industrial Average plunged -0.33%, and the S&P500 fell -1.21%. In dollar amounts, \\$136 billion of market cap evaporated (Domm).

However, there were no other tweets or headlines about the story. Could the Associated Press be that much quicker than all the other global news sources? Surely, such a story would have received wide media coverage. If we insisted on having consistent data sources, we would anticipate a second data source providing the same news. There was none because it was fake news due to a hacked account. The White House quickly confirmed there was no incident. Within six minutes, stocks returned to their normal levels. However, the turbulence for those 6 minutes was enough to wipe out more than $22 billion per minute! Most of the trading was performed by automated trading rules, which were likely to react first rather than "wait for confirmation" later.  

Consider a different example: credit scoring individuals applying for a loan. We can enforce consistency by comparing credit scores from different sources. For example, there are three major credit agencies that provide FICO scores for individuals. While the "true" value is never known, we can compare all 3 scores. Many lenders may use a median score as a means to resolve any discrepancies. Therefore, redundancy in data sources is a good practice.

### **2.4 Timeliness**
The last point concerns the timeliness of data. Arguably, this is the most difficult issue in finance, because financial models built with data can easily become "miscalibrated". Finance is not physics. In physics, the laws of the universe are largely invariant over time. Data we collected yesterday can be used to construct a model that would likely work just as well tomorrow as it does today. Finance, however, is not physics but social science. In social science, laws are replaced by "principles" or "rules" by which humans tend to behave and make decisions.  However, people change their behavior and their decision-making, so models that work one day in finance may not necessarily work the next–-either because a new calibration is needed or perhaps because the model as a whole is no longer appropriate.  
For example, several years ago, the app Google Maps suggested a shortcut for commuters driving to New York City over the George Washington Bridge. At first, only a few drivers followed this shortcut. But as Google Maps and other navigation apps had wider adoption, more and more drivers took this shortcut. It reached a point where the shortcut became just the opposite: traffic congestion. The town attempted to ban out-of-town drivers from using their roads. When people learn of shortcuts, tricks, and secrets, they can change their behavior in a way that effectively eliminates the short cut (Foderaro).

In market terms, if there is arbitrage ('extra time'), as market participants learn and exploit it, it goes away: a restoration of market efficiency. As financial engineers, the price we pay is a constant and healthy amount of skepticism: How can we know that the data we collected continues to accurately represent the way the system works today?

In [1]:
# The FX market is open 24 hours a day, 5 days a week.
# Let's get the most recent FX data: Japanese Yen to Eurodollars
import yfinance as yf

data = yf.download(tickers="JPYAUD=X", period="1d", interval="15m")
data

[*********************100%%**********************]  1 of 1 completed

                         Open      High       Low     Close  Adj Close  Volume
Datetime
2024-09-10 00:00:00  0.010482  0.010485  0.010481  0.010485   0.010485       0
2024-09-10 00:15:00  0.010484  0.010484  0.010473  0.010475   0.010475       0
2024-09-10 00:30:00  0.010473  0.010475  0.010470  0.010474   0.010474       0
2024-09-10 00:45:00  0.010473  0.010486  0.010472  0.010485   0.010485       0
2024-09-10 01:00:00  0.010486  0.010497  0.010485  0.010497   0.010497       0
...                       ...       ...       ...       ...        ...     ...
2024-09-10 20:15:00  0.010546  0.010546  0.010543  0.010545   0.010545       0
2024-09-10 20:30:00  0.010546  0.010550  0.010545  0.010550   0.010550       0
2024-09-10 20:45:00  0.010548  0.010550  0.010545  0.010548   0.010548       0
2024-09-10 21:00:00  0.010546  0.010549  0.010546  0.010549   0.010549       0
2024-09-10 21:15:00  0.010549  0.010553  0.010549  0.010553   0.010553       0

[86 rows x 6 columns]

## **3. Unstructured Data**

As we move to unstructured data, we see that the same principles apply.  Let's discuss what makes data unstructured.  Unlike structured data, unstructured data lacks a predefined format.  It tends to be qualitative, but can be numeric.  It is disjoint, disorganized, complex.  The key distinction is that the data isn't easily placed into a tabular format that relational databases expect.  Rules of thumb in the industry estimate that approximately 80% of all data is unstructured.    
a.	Business Documents
b.	Product Photos or Barcodes
c.	Audio Clips
d.	Videos
e.	Reviews
f.	Social Media
g.	Customer Feedback
h.	Web pages
Some data may lie in between structured and unstructured.  Emails are considered semi-structured because they contain some known fields: sender, recipient, header, and message.  However, within the message field, the data is unstructured and cannot easily be parsed using traditional methods.

## **4. Alternative Data**
Finance has often referred to unstructured data as alternative data. Let's look at some examples. Suppose you are pricing weather derivatives. How do you construct hedges? For example, [one bank uses NASA satellite imagery for pricing and hedging weather derivatives](https://www.artemis.bm/news/mitsui-sumitomo-to-use-nasa-satellites-for-weather-derivative-sales/).  
Consider sentiment analysis for social media. Social media contains many unstructured data fields we discussed in the previous section. Those data need to be captured, from which a rigorous sentiment analysis can be performed.  Please read the paper by Hansen on alternative data and sentiment analysis.

### **4.1 Properties of Alternative Data**
What are the properties of alternative data?  We can list at least half a dozen:

1.   They tend to be unstructured
2.   They tend to be less commonly used in traditional finance
3. Many of the sources (but not all) come from non-financial markets
4. Many of the data contain rare or extreme events
5. Many contain non-textual information, such as audio, video, or imagery
6. They may be the exclusive source of this information



### **4.2  Quality of Alternative Data**
The same principles of accuracy, consistency, completeness, and timeliness apply to unstructured data. However, these can be harder to assert if there is only one source. As an example, an artist with some extra time on his hands decided to trick Google Maps. He collected 99 iPhones, put them in a wagon, and walked them up and down the street in Berlin in front of the Google headquarters. With many phones moving that slowly, Google Maps reported a massive traffic jam--though there were no cars on the road! (Somos)

Fake reviews abound. A food writer, also with a lot of extra time, created a "fake restaurant" and wrote fake reviews of it. Despite there being no physical restaurant there, the restaurant became TripAdvisor's No. 1 ranked restaurant in London! (Bender)
We could look at these events as pranks played by artists.  But the Flash Crash is no different--trades entered by a spoofer who caused a trillion dollars of market swings.  Read the Akansu paper "The Flash Crash: A Review."
We'll conclude this section with a review of the data.

### **4.3 Assessing Alternative Data**
Consider some questions to ask about alternative data.
Who generates the data?
Who collects the data?  
How is it recorded?
Who has access to the data?
How can it be verified?

In [2]:
# Let's look at a few fundamentals on Uber.
from yahooquery import Ticker

uber = Ticker("UBER")

In [3]:
uber.asset_profile  # Uber profile

{'UBER': {'address1': '1725 3rd Street',
  'city': 'San Francisco',
  'state': 'CA',
  'zip': '94158',
  'country': 'United States',
  'phone': '415 612 8582',
  'website': 'https://www.uber.com',
  'industry': 'Software - Application',
  'industryKey': 'software-application',
  'industryDisp': 'Software - Application',
  'sector': 'Technology',
  'sectorKey': 'technology',
  'sectorDisp': 'Technology',
  'longBusinessSummary': 'Uber Technologies, Inc. develops and operates proprietary technology applications in the United States, Canada, Latin America, Europe, the Middle East, Africa, and Asia excluding China and Southeast Asia. It operates through three segments: Mobility, Delivery, and Freight. The Mobility segment connects consumers with a range of transportation modalities, such as ridesharing, carsharing, micromobility, rentals, public transit, taxis, and other modalities; and offers riders in a variety of vehicle types, as well as financial partnerships products and advertising services. The Delivery segment allows to search for and discover restaurants to grocery, alcohol, convenience, and other retails; order a meal or other items; and Uber direct, a white-label Delivery-as-a-Service for retailers and restaurants, as well as advertising. The Freight segment manages transportation and logistics network, which connects shippers and carriers in digital marketplace including carriers upfronts, pricing, and shipment booking; and provides on-demand platform to automate logistics end-to-end transactions for small-and medium-sized business to global enterprises. The company was formerly known as Ubercab, Inc. and changed its name to Uber Technologies, Inc. in February 2011. Uber Technologies, Inc. was founded in 2009 and is headquartered in San Francisco, California.',
  'fullTimeEmployees': 30400,
  'companyOfficers': [{'maxAge': 1,
    'name': 'Mr. Dara  Khosrowshahi',
    'age': 53,
    'title': 'CEO & Director',
    'yearBorn': 1970,
    'fiscalYear': 2023,
    'totalPay': 4437790,
    'exercisedValue': 0,
    'unexercisedValue': 23882328},
   {'maxAge': 1,
    'name': 'Mr. Prashanth  Mahendra-Rajah',
    'age': 53,
    'title': 'Chief Financial Officer',
    'yearBorn': 1970,
    'fiscalYear': 2023,
    'totalPay': 1268902,
    'exercisedValue': 0,
    'unexercisedValue': 0},
   {'maxAge': 1,
    'name': 'Mr. Derek Anthony West J.D.',
    'age': 57,
    'title': 'Senior VP, Chief Legal Officer & Corporate Secretary',
    'yearBorn': 1966,
    'fiscalYear': 2023,
    'totalPay': 3349835,
    'exercisedValue': 0,
    'unexercisedValue': 0},
   {'maxAge': 1,
    'name': 'Ms. Jill  Hazelbaker',
    'age': 41,
    'title': 'Chief Marketing Officer and Senior Vice President of Communications & Public Policy',
    'yearBorn': 1982,
    'fiscalYear': 2023,
    'totalPay': 2079979,
    'exercisedValue': 0,
    'unexercisedValue': 0},
   {'maxAge': 1,
    'name': 'Ms. Nikki  Krishnamurthy',
    'age': 50,
    'title': 'Senior VP & Chief People Officer',
    'yearBorn': 1973,
    'fiscalYear': 2023,
    'totalPay': 2060493,
    'exercisedValue': 0,
    'unexercisedValue': 0},
   {'maxAge': 1,
    'name': 'Mr. Garrett  Camp',
    'age': 44,
    'title': 'Co-Founder, Board Observer & Product Advisor',
    'yearBorn': 1979,
    'fiscalYear': 2023,
    'totalPay': 18033,
    'exercisedValue': 0,
    'unexercisedValue': 0},
   {'maxAge': 1,
    'name': 'Mr. Glen  Ceremony',
    'age': 56,
    'title': 'Chief Accounting Officer & Global Corporate Controller',
    'yearBorn': 1967,
    'fiscalYear': 2023,
    'exercisedValue': 0,
    'unexercisedValue': 0},
   {'maxAge': 1,
    'name': 'Mr. Sundeep  Jain',
    'age': 53,
    'title': 'Chief Product Officer & Senior VP of Engineering',
    'yearBorn': 1970,
    'fiscalYear': 2023,
    'exercisedValue': 0,
    'unexercisedValue': 0},
   {'maxAge': 1,
    'name': 'Mr. Alaxandar  Wang',
    'title': 'Head of Investor Relations',
    'fiscalYear': 2023,
    'exercisedValue': 0,
    'unexercisedValue': 0},
   {'maxAge': 1,
    'name': 'Mr. Scott  Schools',
    'title': 'Chief Compliance and Ethics Officer',
    'fiscalYear': 2023,
    'exercisedValue': 0,
    'unexercisedValue': 0}],
  'auditRisk': 4,
  'boardRisk': 9,
  'compensationRisk': 9,
  'shareHolderRightsRisk': 7,
  'overallRisk': 8,
  'governanceEpochDate': '2024-09-01 00:00:00',
  'compensationAsOfEpochDate': '2023-12-31 00:00:00',
  'maxAge': 86400}}

In [4]:
uber.financial_data  # Uber financial data

{'UBER': {'maxAge': 86400,
  'currentPrice': 68.99,
  'targetHighPrice': 102.0,
  'targetLowPrice': 66.0,
  'targetMeanPrice': 87.02,
  'targetMedianPrice': 89.0,
  'recommendationMean': 1.9,
  'recommendationKey': 'buy',
  'numberOfAnalystOpinions': 46,
  'totalCash': 6291999744,
  'totalCashPerShare': 2.995,
  'ebitda': 2796999936,
  'totalDebt': 11297000448,
  'quickRatio': 1.034,
  'currentRatio': 1.21,
  'totalRevenue': 40058998784,
  'debtToEquity': 81.963,
  'revenuePerShare': 19.36,
  'returnOnAssets': 0.03331,
  'returnOnEquity': 0.19178,
  'freeCashflow': 3908750080,
  'operatingCashflow': 5024999936,
  'earningsGrowth': 1.541,
  'revenueGrowth': 0.159,
  'grossMargins': 0.32372,
  'ebitdaMargins': 0.06982,
  'operatingMargins': 0.07439,
  'profitMargins': 0.0502,
  'financialCurrency': 'USD'}}

In [5]:
uber.key_stats  # Uber KPIs

{'UBER': {'maxAge': 1,
  'priceHint': 2,
  'enterpriseValue': 153083412480,
  'forwardPE': 31.076574,
  'profitMargins': 0.0502,
  'floatShares': 2095768923,
  'sharesOutstanding': 2100940032,
  'sharesShort': 50267561,
  'sharesShortPriorMonth': 49300126,
  'sharesShortPreviousMonthDate': '2024-07-15 00:00:00',
  'dateShortInterest': '2024-08-15 00:00:00',
  'sharesPercentSharesOut': 0.0239,
  'heldPercentInsiders': 0.0018000001,
  'heldPercentInstitutions': 0.83532,
  'shortRatio': 2.55,
  'shortPercentOfFloat': 0.0248,
  'beta': 1.331,
  'impliedSharesOutstanding': 2100940032,
  'category': None,
  'bookValue': 5.887,
  'priceToBook': 11.719042,
  'fundFamily': None,
  'legalType': None,
  'lastFiscalYearEnd': '2023-12-31 00:00:00',
  'nextFiscalYearEnd': '2024-12-31 00:00:00',
  'mostRecentQuarter': '2024-06-30 00:00:00',
  'earningsQuarterlyGrowth': 1.576,
  'netIncomeToCommon': 2011000064,
  'trailingEps': 0.92,
  'forwardEps': 2.22,
  'pegRatio': 1.41,
  'lastSplitFactor': None,
  'enterpriseToRevenue': 3.821,
  'enterpriseToEbitda': 54.731,
  '52WeekChange': 0.45659435,
  'SandP52WeekChange': 0.22617042}}

In [6]:
uber.balance_sheet()  # Uber Balance Sheet

,asOfDate,periodType,currencyCode,AccountsPayable,AccountsReceivable,AccumulatedDepreciation,AdditionalPaidInCapital,AllowanceForDoubtfulAccountsReceivable,AssetsHeldForSaleCurrent,AvailableForSaleSecurities,...,TotalAssets,TotalCapitalization,TotalDebt,TotalEquityGrossMinorityInterest,TotalLiabilitiesNetMinorityInterest,TotalNonCurrentAssets,TotalNonCurrentLiabilitiesNetMinorityInterest,TotalTaxPayable,TradeandOtherPayablesNonCurrent,WorkingCapital
symbol,,,,,,,,,,,,,,,,,,,,,
UBER,2019-12-31,12M,USD,NaN,NaN,NaN,NaN,NaN,0.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,70000000.0,NaN
UBER,2020-12-31,12M,USD,235000000.0,1.073000e+09,-1.016000e+09,3.593100e+10,-55000000.0,517000000.0,6.628000e+09,...,3.325200e+10,1.982600e+10,9.627000e+09,1.375400e+10,1.949800e+10,2.337000e+10,1.263300e+10,2.014000e+09,95000000.0,3.017000e+09
UBER,2021-12-31,12M,USD,860000000.0,2.439000e+09,-1.182000e+09,3.860800e+10,-51000000.0,0.0,7.853000e+09,...,3.877400e+10,2.373400e+10,1.110500e+10,1.534900e+10,2.342500e+10,2.995500e+10,1.440100e+10,2.563000e+09,NaN,-2.050000e+08
UBER,2022-12-31,12M,USD,728000000.0,2.779000e+09,-1.285000e+09,4.055000e+10,-80000000.0,NaN,4.291000e+09,...,3.210900e+10,1.660500e+10,1.113900e+10,8.504000e+09,2.360500e+10,2.286000e+10,1.475200e+10,2.049000e+09,NaN,3.960000e+08
UBER,2023-12-31,12M,USD,790000000.0,3.404000e+09,-1.401000e+09,4.226400e+10,-91000000.0,NaN,5.975000e+09,...,3.869900e+10,2.070800e+10,1.119900e+10,1.268200e+10,2.601700e+10,2.740200e+10,1.656300e+10,1.728000e+09,NaN,1.843000e+09

In [7]:
uber.cash_flow(trailing=False)  # Uber Cask Flow

,asOfDate,periodType,currencyCode,AssetImpairmentCharge,BeginningCashPosition,CapitalExpenditure,CashFlowFromContinuingFinancingActivities,CashFlowFromContinuingInvestingActivities,CashFlowFromContinuingOperatingActivities,ChangeInAccountPayable,...,PurchaseOfInvestment,PurchaseOfPPE,RepaymentOfDebt,RepurchaseOfCapitalStock,SaleOfBusiness,SaleOfInvestment,SaleOfPPE,ShortTermDebtIssuance,StockBasedCompensation,UnrealizedGainLossOnInvestmentSecurities
symbol,,,,,,,,,,,,,,,,,,,,,
UBER,2019-12-31,12M,USD,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,-74000000.0,NaN,NaN,51000000.0,0.0,NaN,NaN
UBER,2020-12-31,12M,USD,2.170000e+09,1.206700e+10,-616000000.0,1.379000e+09,-2.869000e+09,-2.745000e+09,-133000000.0,...,-2.111000e+09,-616000000.0,-1.642000e+09,0.0,9.100000e+07,1.360000e+09,3000000.0,NaN,8.270000e+08,1.250000e+08
UBER,2021-12-31,12M,USD,2.250000e+08,7.391000e+09,-298000000.0,1.780000e+09,-1.201000e+09,-4.450000e+08,90000000.0,...,-2.095000e+09,-298000000.0,-8.420000e+08,NaN,1.000000e+09,2.791000e+09,NaN,NaN,1.168000e+09,-1.142000e+09
UBER,2022-12-31,12M,USD,3.240000e+08,7.805000e+09,-252000000.0,1.500000e+07,-1.637000e+09,6.420000e+08,-133000000.0,...,-1.722000e+09,-252000000.0,-2.640000e+08,NaN,2.600000e+07,3.760000e+08,NaN,NaN,1.793000e+09,7.045000e+09
UBER,2023-12-31,12M,USD,1.780000e+08,6.677000e+09,-223000000.0,-9.500000e+07,-3.226000e+09,3.585000e+09,64000000.0,...,-8.826000e+09,-223000000.0,-2.871000e+09,NaN,7.210000e+08,5.069000e+09,NaN,NaN,1.935000e+09,-1.610000e+09

In [8]:
uber.income_statement()  # Uber Income Statement

,asOfDate,periodType,currencyCode,AverageDilutionEarnings,BasicAverageShares,BasicEPS,CostOfRevenue,DepreciationAmortizationDepletionIncomeStatement,DepreciationAndAmortizationInIncomeStatement,DilutedAverageShares,...,SpecialIncomeCharges,TaxEffectOfUnusualItems,TaxProvision,TaxRateForCalcs,TotalExpenses,TotalOperatingIncomeAsReported,TotalRevenue,TotalUnusualItems,TotalUnusualItemsExcludingGoodwill,WriteOff
symbol,,,,,,,,,,,,,,,,,,,,,
UBER,2019-12-31,12M,USD,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
UBER,2020-12-31,12M,USD,0.0,1.752960e+09,-3.86,5.154000e+09,575000000.0,575000000.0,1.752960e+09,...,-1.486000e+09,-4.869200e+07,-192000000.0,0.028000,1.600200e+10,-4.863000e+09,1.113900e+10,-1.739000e+09,-1.739000e+09,1.690000e+09
UBER,2021-12-31,12M,USD,-44000000.0,1.892546e+09,-0.26,9.351000e+09,902000000.0,902000000.0,1.895519e+09,...,1.684000e+09,8.564400e+08,-492000000.0,0.270000,2.128900e+10,-3.834000e+09,1.745500e+10,3.172000e+09,3.172000e+09,0.000000e+00
UBER,2022-12-31,12M,USD,-41000000.0,1.972131e+09,-4.64,1.965900e+10,947000000.0,947000000.0,1.974928e+09,...,-1.680000e+08,-1.362110e+08,-181000000.0,0.019000,3.370900e+10,-1.832000e+09,3.187700e+10,-7.169000e+09,-7.169000e+09,1.820000e+08
UBER,2023-09-30,TTM,USD,NaN,2.019130e+09,0.55,NaN,NaN,NaN,2.059272e+09,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
UBER,2023-12-31,12M,USD,-60000000.0,2.035651e+09,0.93,2.245700e+10,823000000.0,823000000.0,2.091782e+09,...,2.040000e+08,1.433360e+08,213000000.0,0.092000,3.617100e+10,1.110000e+09,3.728100e+10,1.558000e+09,1.558000e+09,0.000000e+00
UBER,2023-12-31,TTM,USD,NaN,2.035651e+09,0.93,NaN,NaN,NaN,2.091782e+09,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
UBER,2024-03-31,TTM,USD,NaN,2.052878e+09,0.70,NaN,NaN,NaN,2.109435e+09,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
UBER,2024-06-30,TTM,USD,-63000000.0,2.069196e+09,0.98,2.433900e+10,771000000.0,771000000.0,2.134476e+09,...,NaN,2.804406e+07,179000000.0,0.073031,3.804500e+10,2.014000e+09,4.005900e+10,3.840000e+08,3.840000e+08,NaN

## **5. The Big Data: The 5 Vs**

In the field of data science, machine learning has provided best practices of data for more than 20 years. There is a well-known "Big 5 Vs." (Some papers point to dozens and dozens of Vs!) We'll discuss these five features. (Please see the Ishwarappa paper for more details.)

* **Volume**

    Volume is the amount of data. Streams and streams of data pour in.

* **Variety**

    Variety refers to the different sources and forms. In our previous sections, we saw that data can be structured, semi-structured, or unstructured.

* **Velocity**

    Velocity refers to the rate at which data is created in real time. Exchange data can be as fast as fractions of a millisecond! Other financial data may not be
    available more than once a day or even quarterly in the case of economic indicators.

* **Veracity**

    Veracity refers to the confidence in the data source.  Think fake news accounts and spoofed trades.

* **Value**

    Value refers to the insights available in the data.  

## **6. Conclusion**

Data science has influenced every field due to its universal nature of addressing data collection, visualization, modeling, and presentation. Financial engineering is no exception. As financial engineers, we'll examine machine learning problems through a financial lens and follow the best practices for data that have been recommended in both fields.

**References**

*   Bender, Andrew. TripAdvisor Gets Totally Punked when Fake Restaurant is Ranked No. 1. *Forbes*, December 8, 2017.  
https://www.forbes.com/sites/andrewbender/2017/12/08/tripadvisor-gets-totally-punked-when-fake-restaurant-is-ranked-no-1/?sh=2d5d01282c23

* Domm, Patti. "False Rumor of Explosion at White House Causes Stocks to Briefly Plunge; AP Confirms Its Twitter Feed Was Hacked." *CNBC*, 24 Apr. 2013, www.cnbc.com/id/100646197.

* Foderaro, Lisa. "Navigation Apps Are Turning Quiet Neighborhoods Into Traffic Nightmares." *The New York Times*, 24 Dec. 2017, www.nytimes.com/2017/12/24/nyregion/traffic-apps-gps-neighborhoods.html.

*   Somos, Christy. German Artist Uses 99 Smartphones to Fool Google Maps with Fake Traffic Jam. *Sci-Tech News*, February 4, 2020.
https://www.ctvnews.ca/sci-tech/german-artist-uses-99-smartphones-to-fool-google-maps-with-fake-traffic-jam-1.4797313?cache=yes%3FclipId%3D89619%2Fexpert-advice-5-ways-to-get-rid-of-annoying-fruit-flies-1.2492904

---
Copyright 2024 WorldQuant University. This
content is licensed solely for personal use. Redistribution or
publication of this material is strictly prohibited.